#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProfileHG.Resource", IsApplication=true)]

namespace ProfileHG
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_achievement = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_alarm = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_amazon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_anchor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_android = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_armchair = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_arrow_bottom = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_arrow_left = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_arrow_left_bottom = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_arrow_left_top = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_arrow_right = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_arrow_right_bottom = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_arrow_right_top = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_arrow_top = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_attachment = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_attachment_2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_ball = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_balloon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_barcode_1 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_barcode_2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_bargraph = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_bars = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_action_basket = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_action_bell = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_action_bike = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_action_blob = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_bluetooth = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_book = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_action_bookmark = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_action_box = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_action_brush = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_action_bug = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_action_bulb = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_action_bus = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_action_business = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_action_calculator = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_action_calendar_day = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_action_calendar_month = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_action_camera = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_action_cancel = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_action_car = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_cart = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_action_circles = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_action_clock = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_action_cloud = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_action_cloudy = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_action_coffee = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_action_coffee2go = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_action_collapse = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_action_compass = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_action_contrast = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_action_copy = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_action_creditcard = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_action_crop = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_action_cut = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_action_database = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_action_dialer = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_action_dialog = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_action_dice1 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_action_dice2 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_action_dice3 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_action_dice4 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_action_dice5 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_action_dice6 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_action_document = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_action_dontlike = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_action_download = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_action_drag = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_action_drop = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_action_dropbox = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic_action_edit = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ic_action_emo_angry = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ic_action_emo_basic = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ic_action_emo_cool = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ic_action_emo_cry = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ic_action_emo_err = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ic_action_emo_evil = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ic_action_emo_kiss = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ic_action_emo_laugh = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ic_action_emo_shame = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ic_action_emo_tongue = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ic_action_emo_wink = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ic_action_emo_wonder = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ic_action_exit = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int ic_action_expand = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int ic_action_export = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int ic_action_eye_closed = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int ic_action_eye_open = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int ic_action_facebook = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int ic_action_feed = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int ic_action_filter = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int ic_action_flag = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int ic_action_flags = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int ic_action_flash = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ic_action_folder_closed = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int ic_action_folder_open = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int ic_action_folder_tabs = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int ic_action_font_bigger = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int ic_action_font_bold = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int ic_action_font_faces = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int ic_action_font_italic = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int ic_action_font_smaller = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ic_action_font_underline = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int ic_action_foursquare = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ic_action_gear = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int ic_action_github = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int ic_action_glasses = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int ic_action_globe = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int ic_action_gmail = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int ic_action_goleft = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int ic_action_google_play = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int ic_action_goright = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int ic_action_gplus = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int ic_action_grow = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int ic_action_guitar = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int ic_action_halt = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int ic_action_headphones = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int ic_action_heart = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int ic_action_help = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int ic_action_home = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int ic_action_html5 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int ic_action_import = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int ic_action_inbox = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int ic_action_info = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int ic_action_io = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int ic_action_joypad = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int ic_action_key = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int ic_action_knight = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int ic_action_lab = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int ic_action_laptop = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int ic_action_like = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int ic_action_line_chart = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int ic_action_link = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int ic_action_linkedin = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int ic_action_list = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int ic_action_list_2 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int ic_action_location = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int ic_action_location_2 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int ic_action_lock_closed = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int ic_action_lock_open = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int ic_action_magnet = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int ic_action_mail = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int ic_action_map = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int ic_action_mic = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int ic_action_micoff = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int ic_action_minus = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int ic_action_mist = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int ic_action_monitor = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int ic_action_monolog = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int ic_action_more = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int ic_action_mouse = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int ic_action_movie = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int ic_action_music_1 = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int ic_action_music_2 = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int ic_action_mustache = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int ic_action_navigate = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int ic_action_news = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int ic_action_overflow = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int ic_action_paste = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int ic_action_paypal = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int ic_action_phone = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int ic_action_phone_end = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int ic_action_phone_incoming = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int ic_action_phone_missed = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int ic_action_phone_outgoing = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int ic_action_phone_start = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int ic_action_picker = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int ic_action_picture = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int ic_action_pie_chart = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int ic_action_pill = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int ic_action_pin = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int ic_action_pinterest = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int ic_action_plane = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int ic_action_planet = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int ic_action_playback_forw = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int ic_action_playback_next = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int ic_action_playback_pause = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int ic_action_playback_play = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int ic_action_playback_prev = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int ic_action_playback_repeat = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int ic_action_playback_repeat_1 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int ic_action_playback_rew = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int ic_action_playback_schuffle = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int ic_action_playback_stop = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int ic_action_plug = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int ic_action_plusone = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int ic_action_present = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int ic_action_process_end = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int ic_action_process_save = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int ic_action_process_start = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int ic_action_puzzle = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int ic_action_rain = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int ic_action_record = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int ic_action_redo = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int ic_action_reload = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int ic_action_restaurant = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int ic_action_rocket = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int ic_action_ruler = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int ic_action_save = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int ic_action_search = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int ic_action_send = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int ic_action_settings = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int ic_action_share = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int ic_action_share_2 = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int ic_action_shield = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int ic_action_signal = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int ic_action_sms = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int ic_action_sort_1 = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public const int ic_action_sort_2 = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public const int ic_action_soundcloud = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public const int ic_action_stamp = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public const int ic_action_star_0 = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public const int ic_action_star_10 = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public const int ic_action_star_5 = 2130837718;
			
			// aapt resource value: 0x7f0200d7
			public const int ic_action_stumbleupon = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public const int ic_action_sun = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public const int ic_action_tablet = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public const int ic_action_tag = 2130837722;
			
			// aapt resource value: 0x7f0200db
			public const int ic_action_tags = 2130837723;
			
			// aapt resource value: 0x7f0200dc
			public const int ic_action_temperature = 2130837724;
			
			// aapt resource value: 0x7f0200dd
			public const int ic_action_tick = 2130837725;
			
			// aapt resource value: 0x7f0200de
			public const int ic_action_ticket = 2130837726;
			
			// aapt resource value: 0x7f0200df
			public const int ic_action_tiles_large = 2130837727;
			
			// aapt resource value: 0x7f0200e0
			public const int ic_action_tiles_small = 2130837728;
			
			// aapt resource value: 0x7f0200e1
			public const int ic_action_train = 2130837729;
			
			// aapt resource value: 0x7f0200e2
			public const int ic_action_trash = 2130837730;
			
			// aapt resource value: 0x7f0200e3
			public const int ic_action_tshirt = 2130837731;
			
			// aapt resource value: 0x7f0200e4
			public const int ic_action_tumblr = 2130837732;
			
			// aapt resource value: 0x7f0200e5
			public const int ic_action_turn_left = 2130837733;
			
			// aapt resource value: 0x7f0200e6
			public const int ic_action_turn_right = 2130837734;
			
			// aapt resource value: 0x7f0200e7
			public const int ic_action_tv = 2130837735;
			
			// aapt resource value: 0x7f0200e8
			public const int ic_action_twitter = 2130837736;
			
			// aapt resource value: 0x7f0200e9
			public const int ic_action_umbrella = 2130837737;
			
			// aapt resource value: 0x7f0200ea
			public const int ic_action_undo = 2130837738;
			
			// aapt resource value: 0x7f0200eb
			public const int ic_action_upload = 2130837739;
			
			// aapt resource value: 0x7f0200ec
			public const int ic_action_user = 2130837740;
			
			// aapt resource value: 0x7f0200ed
			public const int ic_action_users = 2130837741;
			
			// aapt resource value: 0x7f0200ee
			public const int ic_action_video = 2130837742;
			
			// aapt resource value: 0x7f0200ef
			public const int ic_action_vimeo = 2130837743;
			
			// aapt resource value: 0x7f0200f0
			public const int ic_action_volume = 2130837744;
			
			// aapt resource value: 0x7f0200f1
			public const int ic_action_volume_down = 2130837745;
			
			// aapt resource value: 0x7f0200f2
			public const int ic_action_volume_mute = 2130837746;
			
			// aapt resource value: 0x7f0200f3
			public const int ic_action_volume_up = 2130837747;
			
			// aapt resource value: 0x7f0200f4
			public const int ic_action_warning = 2130837748;
			
			// aapt resource value: 0x7f0200f5
			public const int ic_action_wheel = 2130837749;
			
			// aapt resource value: 0x7f0200f6
			public const int ic_action_wifi = 2130837750;
			
			// aapt resource value: 0x7f0200f7
			public const int ic_action_wizard = 2130837751;
			
			// aapt resource value: 0x7f0200f8
			public const int ic_action_yinyang = 2130837752;
			
			// aapt resource value: 0x7f0200f9
			public const int ic_action_youtube = 2130837753;
			
			// aapt resource value: 0x7f0200fa
			public const int Icon = 2130837754;
			
			// aapt resource value: 0x7f0200fb
			public const int ProfileHogBackground = 2130837755;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050032
			public const int ActiveButtonLayout = 2131034162;
			
			// aapt resource value: 0x7f05004f
			public const int ContentLayout = 2131034191;
			
			// aapt resource value: 0x7f050002
			public const int DetailsDetails = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int DetailsLayout = 2131034112;
			
			// aapt resource value: 0x7f050035
			public const int DetailsMenuButton = 2131034165;
			
			// aapt resource value: 0x7f050033
			public const int DetailsMenuLayout = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int DetailsMenuText = 2131034164;
			
			// aapt resource value: 0x7f050001
			public const int DetailsScroll = 2131034113;
			
			// aapt resource value: 0x7f050027
			public const int GraphLayout = 2131034151;
			
			// aapt resource value: 0x7f050031
			public const int GraphMenuButton = 2131034161;
			
			// aapt resource value: 0x7f05002f
			public const int GraphMenuLayout = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int GraphMenuText = 2131034160;
			
			// aapt resource value: 0x7f05004b
			public const int HeaderLayout = 2131034187;
			
			// aapt resource value: 0x7f05004a
			public const int MainParent = 2131034186;
			
			// aapt resource value: 0x7f05002d
			public const int MenuBarLayout = 2131034157;
			
			// aapt resource value: 0x7f05004e
			public const int NavigationLayout = 2131034190;
			
			// aapt resource value: 0x7f050052
			public const int QuickView = 2131034194;
			
			// aapt resource value: 0x7f050054
			public const int QuickViewGroup = 2131034196;
			
			// aapt resource value: 0x7f050051
			public const int QuickViewLayout = 2131034193;
			
			// aapt resource value: 0x7f050050
			public const int QuickViewLayoutParent = 2131034192;
			
			// aapt resource value: 0x7f050053
			public const int QuickViewScroll = 2131034195;
			
			// aapt resource value: 0x7f050037
			public const int TemeratureMenuText = 2131034167;
			
			// aapt resource value: 0x7f050057
			public const int TemperatureDetails = 2131034199;
			
			// aapt resource value: 0x7f050055
			public const int TemperatureLayout = 2131034197;
			
			// aapt resource value: 0x7f050038
			public const int TemperatureMenuButton = 2131034168;
			
			// aapt resource value: 0x7f050036
			public const int TemperatureMenuLayout = 2131034166;
			
			// aapt resource value: 0x7f050056
			public const int TemperatureScroll = 2131034198;
			
			// aapt resource value: 0x7f05002a
			public const int TitleBarLayout = 2131034154;
			
			// aapt resource value: 0x7f05004c
			public const int TitleLayout = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int TitleText = 2131034189;
			
			// aapt resource value: 0x7f05002c
			public const int appTitleText = 2131034156;
			
			// aapt resource value: 0x7f050004
			public const int counterTitleRow = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int cpuAverage = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int cpuCurrent = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int cpuHighest = 2131034124;
			
			// aapt resource value: 0x7f05003c
			public const int cpuQuickView = 2131034172;
			
			// aapt resource value: 0x7f05003f
			public const int cpuQuickViewCurrent = 2131034175;
			
			// aapt resource value: 0x7f05003e
			public const int cpuQuickViewSummary = 2131034174;
			
			// aapt resource value: 0x7f050009
			public const int cpuTableRow = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int cpuTitle = 2131034122;
			
			// aapt resource value: 0x7f050044
			public const int diskQuickView = 2131034180;
			
			// aapt resource value: 0x7f050046
			public const int diskQuickViewCurrent = 2131034182;
			
			// aapt resource value: 0x7f050045
			public const int diskQuickViewSummary = 2131034181;
			
			// aapt resource value: 0x7f050017
			public const int diskReadAverage = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int diskReadCurrent = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int diskReadHighest = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int diskReadTableRow = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int diskReadTitle = 2131034132;
			
			// aapt resource value: 0x7f05001c
			public const int diskWriteAverage = 2131034140;
			
			// aapt resource value: 0x7f05001a
			public const int diskWriteCurrent = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int diskWriteHighest = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int diskWriteTableRow = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int diskWriteTitle = 2131034137;
			
			// aapt resource value: 0x7f050039
			public const int frameLayout1 = 2131034169;
			
			// aapt resource value: 0x7f050021
			public const int gpuCoreAverage = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int gpuCoreCurrent = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int gpuCoreHighest = 2131034144;
			
			// aapt resource value: 0x7f05001d
			public const int gpuCoreTableRow = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int gpuCoreTitle = 2131034142;
			
			// aapt resource value: 0x7f050022
			public const int gpuMemTableRow = 2131034146;
			
			// aapt resource value: 0x7f050026
			public const int gpuMemoryAverage = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int gpuMemoryCurrent = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int gpuMemoryHighest = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int gpuMemoryTitle = 2131034147;
			
			// aapt resource value: 0x7f050047
			public const int gpuQuickView = 2131034183;
			
			// aapt resource value: 0x7f050049
			public const int gpuQuickViewCurrent = 2131034185;
			
			// aapt resource value: 0x7f050048
			public const int gpuQuickViewSummary = 2131034184;
			
			// aapt resource value: 0x7f05002b
			public const int imageButton1 = 2131034155;
			
			// aapt resource value: 0x7f050029
			public const int linearLayout1 = 2131034153;
			
			// aapt resource value: 0x7f05003a
			public const int linearLayout10 = 2131034170;
			
			// aapt resource value: 0x7f05002e
			public const int linearLayout11 = 2131034158;
			
			// aapt resource value: 0x7f050059
			public const int linearLayout2 = 2131034201;
			
			// aapt resource value: 0x7f05003d
			public const int linearLayout9 = 2131034173;
			
			// aapt resource value: 0x7f050003
			public const int performanceCounterTable = 2131034115;
			
			// aapt resource value: 0x7f05003b
			public const int quickViewLayout = 2131034171;
			
			// aapt resource value: 0x7f050012
			public const int ramAverage = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int ramCurrent = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int ramHighest = 2131034129;
			
			// aapt resource value: 0x7f050041
			public const int ramQuickView = 2131034177;
			
			// aapt resource value: 0x7f050043
			public const int ramQuickViewCurrent = 2131034179;
			
			// aapt resource value: 0x7f050042
			public const int ramQuickViewSummary = 2131034178;
			
			// aapt resource value: 0x7f05000e
			public const int ramTableRow = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int ramTitle = 2131034127;
			
			// aapt resource value: 0x7f050028
			public const int relativeLayout1 = 2131034152;
			
			// aapt resource value: 0x7f05005a
			public const int tableLayout1 = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int tableRow1 = 2131034203;
			
			// aapt resource value: 0x7f050060
			public const int tableRow2 = 2131034208;
			
			// aapt resource value: 0x7f050058
			public const int textView1 = 2131034200;
			
			// aapt resource value: 0x7f05005c
			public const int textView11 = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int textView12 = 2131034205;
			
			// aapt resource value: 0x7f05005e
			public const int textView13 = 2131034206;
			
			// aapt resource value: 0x7f05005f
			public const int textView14 = 2131034207;
			
			// aapt resource value: 0x7f050061
			public const int textView15 = 2131034209;
			
			// aapt resource value: 0x7f050062
			public const int textView16 = 2131034210;
			
			// aapt resource value: 0x7f050063
			public const int textView17 = 2131034211;
			
			// aapt resource value: 0x7f050064
			public const int textView18 = 2131034212;
			
			// aapt resource value: 0x7f050005
			public const int textView39 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int textView40 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textView41 = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int textView46 = 2131034119;
			
			// aapt resource value: 0x7f050040
			public const int textView48 = 2131034176;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DetailsLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GraphLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ProfileHogMain = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TemperatureLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TemperatureTableTemplate = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int Header_Processes_CPU = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Header_Processes_Name = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int Header_Processes_RAM = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
